### ISSUE TITLE
When in corners, image origins are way off

### ISSUE THREAD

**Issue by Baumchen** [Scianski/KSCustomUIPopover#3]
When placing a button or plain (e.g. plain compose) UIBarButtonItem in the very left/right lower corner the corner radius is not taken into account properly.

Instead of using
// If arrow image exceeds rounded corner arrow image x postion is adjusted
if (arrowImageOriginX + ARROW_WIDTH > self.bounds.size.width - cornerRadius)
{
    arrowImageOriginX -= cornerRadius;
}

if (arrowImageOriginX < cornerRadius)
{
    arrowImageOriginX += cornerRadius;
}

You should be using:
arrowImageOriginX = MIN(arrowImageOriginX, self.bounds.size.width - ARROW_WIDTH - cornerRadius);
arrowImageOriginX = MAX(arrowImageOriginX, cornerRadius);
as there is a max/min value for these origins.
The above code works for up/down.

For left/right use the following:
arrowImageOriginY = MIN(arrowImageOriginY, self.bounds.size.height - ARROW_WIDTH - cornerRadius);
arrowImageOriginY = MAX(arrowImageOriginY, cornerRadius);

**Comment by Scianski** [comment]
Thanks I will add this fix right away.

**Comment by Baumchen** [comment]
Kk thx.
